#!/bin/sh -e

MINKVER="2.6.24"
PREREQ=""
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

# Output pre-requisites
prereqs() {
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# DM / Dynamic Partitions
copy_exec /usr/sbin/dmsetup /sbin
copy_exec /usr/sbin/parse-android-dynparts /sbin

# EXT4
copy_exec /sbin/dumpe2fs /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/resize2fs /sbin

# F2FS
copy_exec /usr/sbin/fsck.f2fs /sbin
copy_exec /usr/sbin/resize.f2fs /sbin

# Libs
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libz.so.1
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libcrypto.so
copy_exec /usr/lib/$DEB_HOST_MULTIARCH/libdl.so

# Tools
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /sbin/swapon /sbin
