name: halium-initramfs
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialize environment
        run: |
          sudo apt-get update
          sudo apt-get install qemu-user-static debootstrap -y

      - name: Build initramfs
        run: sudo ARCH=${{ matrix.arch }} ./build-initrd.sh

      - name : Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: halium-initramfs-${{ matrix.arch }}
          path: out/

  upload:
    needs: build
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v2

      - name: Release to the axolotl-xenial tag.
        uses: softprops/action-gh-release@v1
        with:
          tag_name: axolotl-xenial
          files: halium-initramfs-*/*
          fail_on_unmatched_files: true
